# Generated by Django 4.1 on 2023-04-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked',
            name='naat_khwan',
            field=models.CharField(default='', max_length=200),
        ),
    ]
